#!/usr/bin/python3

import sys
import json
import asyncio
from i3ipc.aio import Connection
from i3ipc import Event


class i3Bifocals:
    def __init__(self):
        self.status = []
        self.focused_name = None

    def print_status(self):
        focus_block = {"name": "focused_con", "full_text": self.focused_name or "-"}
        blocks = [focus_block, *self.status]
        print(json.dumps(blocks) + ",", flush=True)

    def handle_workspace_event(self, i3, event):
        if event.current.find_focused() is None:
            self.focused_name = None
            self.print_status()

    def handle_window_event(self, i3, event):
        if event.change == "focus" or event.change == "title" and event.container.focused:
            self.focused_name = event.container.name
            self.print_status()
        elif event.change == "close":
            self.focused_name = None
            self.print_status()

    async def main(self, argv):
        i3 = await Connection().connect()

        i3.on(Event.WORKSPACE_FOCUS, self.handle_workspace_event)
        for event_type in (Event.WINDOW_FOCUS, Event.WINDOW_TITLE, Event.WINDOW_CLOSE):
            i3.on(event_type, self.handle_window_event)

        tree = await i3.get_tree()
        focused = tree.find_focused()
        if focused.type == "con":
            self.focused_name = focused.name
        else:
            self.focused_name = None

        i3status = await asyncio.create_subprocess_exec(*argv, stdout=asyncio.subprocess.PIPE)

        # our input and output must start with two very specific things (see:
        # https://i3wm.org/docs/i3bar-protocol.html).

        print(json.dumps({"version": 1}))
        print("[")

        # verify that i3status sent the same header to us.

        try:
            header = json.loads(await i3status.stdout.readline())
            assert header["version"] == 1
        except (json.decoder.JSONDecodeError, ValueError):
            print("could not parse JSON header from i3status! exiting.", file=sys.stderr)
            sys.exit(1)
        except AssertionError:
            print("got an unknown i3bar protocol version! exiting.", file=sys.stderr)
            sys.exit(1)

        array_start = await i3status.stdout.read(1)
        if array_start != b"[":
            print("did not read a body from i3status! exiting.", file=sys.stderr)
            sys.exit(1)

        # for this we're cheaping out and stripping instead of using a
        # real streaming parser. note that on the first iteration here,
        # we've only read the opening bracket, so it's possible (and
        # very likely, since it's what i3status does) although not
        # required by the spec that the rest of the line is empty; don't
        # try to parse any JSON in that case.
        #
        # this could be extended to keep a buffer and append to it until
        # we get a whole status line array that we can parse as a JSON
        # value, for implementations that include newlines in their
        # output (i don't think there are any given that the *de facto*
        # spec as consumed by a million little scripts like this one
        # seems to be one status line array per line. just, technically,
        # it's valid and we ought to properly handle it someday).
        #
        # fun fact: i originally wrote this with JSONStreamer in anger!
        # then i calmed down, read the spec again, and decided this
        # would be more illuminating if i dropped that baggage and did
        # things the easy way like a normal person, since the point of
        # this script is demonstrating the use of async IPC, not how we
        # sling the JSON.

        while i3status.returncode is None:
            line_bytes = await i3status.stdout.readline()
            line = line_bytes.decode("utf-8").strip(",\n")
            if line:
                self.status = json.loads(line)
                self.print_status()


if __name__ == "__main__":
    i3status_argv = sys.argv[1:] or ["i3status"]
    try:
        asyncio.run(i3Bifocals().main(i3status_argv))
    except (KeyboardInterrupt, SystemExit):
        sys.exit(0)
